// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace StoreApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231007082535_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Book"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Electronic"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            Price = 11000m,
                            ProductName = "Asus Computer"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Price = 12000m,
                            ProductName = "Hp Notebook"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            Price = 13000m,
                            ProductName = "Iphone 13"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Price = 14000m,
                            ProductName = "Iphone 14"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Price = 15000m,
                            ProductName = "Iphone 15"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Price = 16000m,
                            ProductName = "Iphone 16"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Price = 150m,
                            ProductName = "Angry"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            Price = 250m,
                            ProductName = "Black And Dark"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
